packages:
  - apps/*
  - packages/*

catalog:
  '@types/better-sqlite3': ^7.6.13
  '@types/node': ^22.18.12
  '@vitest/coverage-v8': ^4.0.3
  '@vitest/ui': ^4.0.3
  better-sqlite3: ^12.4.1
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.7
  typescript: ^5.6.3
  vitest: ^4.0.3
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
