packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.9.2
  '@vitest/coverage-v8': ^4.0.3
  '@vitest/ui': ^4.0.3
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.7
  typescript: ^5.9.3
  vitest: ^4.0.3
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
