packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.10.1
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.44.7
  typescript: ^5.9.3
  vitest: ^4.0.15
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
