packages:
  - apps/*
  - packages/*

catalog:
  '@faker-js/faker': ^10.1.0
  '@types/node': ^24.10.1
  '@vitest/browser-playwright': ^4.0.15
  '@vitest/coverage-v8': ^4.0.15
  '@vitest/ui': ^4.0.15
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.45.0
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: ^8.0.0-beta.1
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.15
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
