packages:
  - apps/*
  - packages/*

catalog:
  '@faker-js/faker': ^10.1.0
  '@types/node': ^25.0.3
  '@vitest/browser-playwright': ^4.0.16
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16
  drizzle-kit: ^0.31.5
  drizzle-orm: ^0.45.1
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: ^8.0.0-beta.1
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16
  zod: ^4.2.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
