export const VALIDATION_MESSAGES = {
  GENERIC: {
    INVALID_FORMAT: 'VALIDATION.INVALID_FORMAT',
    REQUIRED: 'VALIDATION.REQUIRED',
  },
  SPECIFIC: {
    EMAIL: {
      INVALID_FORMAT: 'VALIDATION.EMAIL.INVALID_FORMAT',
    },
    PASSWORD: {
      NO_NUMBER: 'VALIDATION.PASSWORD.NO_NUMBER',
      TOO_SHORT: 'VALIDATION.PASSWORD.TOO_SHORT',
    },
    ROLE: {
      INVALID_OPTION: 'VALIDATION.ROLE.INVALID_OPTION',
    },
    UUID: {
      INVALID_FORMAT: 'VALIDATION.UUID.INVALID_FORMAT',
    },
  },
} as const
