export const USER_EMAIL_VALIDATION_MESSAGES = {
  INVALID_FORMAT: 'VALIDATION.USER.EMAIL.INVALID_FORMAT',
  TOO_LONG: 'VALIDATION.USER.EMAIL.TOO_LONG',
  TOO_SHORT: 'VALIDATION.USER.EMAIL.TOO_SHORT',
}
