### Login
# @name login
POST {{protocol}}://{{host}}/api/auth/login
Content-Type: {{jsonContentType}}

{
  "email": "{{superAdminRoleTestEmail}}",
  "password": "{{superAdminRoleTestPassword}}"
}

### Set Auth Tokens
@authToken = {{login.response.body.data.accessToken}}
@refreshToken = {{login.response.body.data.refreshToken}}

### Refresh Token
POST {{protocol}}://{{host}}/api/auth/refresh
Content-Type: {{jsonContentType}}
Authorization: Bearer {{authToken}}

{
  "refreshToken": "{{refreshToken}}"
}

### Logout
POST {{protocol}}://{{host}}/api/auth/logout
Content-Type: {{jsonContentType}}
Authorization: Bearer {{authToken}}

{
  "refreshToken": "{{refreshToken}}"
}
